audit_header: false
title: Jacksonville Real Estate Video Blog with Jeff Riber
description: >-
  You're probably looking for someone to help you make a good decision on your
  next real estate transaction, yes? Theodore Roosevelt (our 26th President) has
  this quote that I love, “Every person who invests in well-selected real estate
  in a growing section of a prosperous community adopts the surest and safest
  method of becoming independent, for real estate is the basis of wealth.” If
  your aim is to improve your well being, and the well being of your family,
  then home-ownership is a great way (if not the best way) to do it!


  We know that good decisions are made with good information. Just like many
  other categories of our economy, residential real estate has become a very
  specialized skill. Making sure that you have a skilled professional alongside
  you when buying or selling is critical. Mistakes can be costly.


  I grew up in Jacksonville (minus 4 years in Virginia getting a degree in
  Finance from Liberty University) and love almost everything about the real
  estate business. I have a tendency to try and do things that people tell me I
  shouldn't. Thus, jumping into the real estate business during the "Great
  Recession" was a pretty predictable move. I've been working as a real estate
  agent since 2007 (prior to that I was in the mortgage business) and became the
  broker/owner of ERA Heavener Realty in 2011. At this point, I'm well past 400
  closings in my career, and have personally bought/sold over 50 homes. In 2010
  I was honored to have been nominated to the Jacksonville Business Journals 40
  Under 40 crew. All of that to say, I've taken all of the bumps and bruises the
  real estate market has to offer, so that I can help you avoid them :)


  In addition to real estate, I love traveling with my wife to cool places,
  hanging out with our little ones (Anniston, Miles, Ava, Lily, and Leighton),
  and playing basketball (even though I have lost a step... Or, two).
show_custom_links: true
custom_links:
  - title: Schedule an Appointment
    url: https://calendly.com/jeffriber/15min
  - title: Testimonials
    url: >-
      https://www.google.com/search?q=era+heavener+realty&rlz=1C1CHBF_enUS702US703&oq=era+heav&aqs=chrome.0.69i59j46i175i199j69i57j69i60j69i61j69i60j69i65l2.1486j1j7&sourceid=chrome&ie=UTF-8
  - title: Guaranteed Offer
    url: /guaranteed-offer/
client:
  name: Jeff Riber
  title: Broker
  license_number: 3235951
  about_markdown: >-
    You're probably looking for someone to help you make a good decision on your
    next real estate transaction, yes? Theodore Roosevelt (our 26th President)
    has this quote that I love, “Every person who invests in well-selected real
    estate in a growing section of a prosperous community adopts the surest and
    safest method of becoming independent, for real estate is the basis of
    wealth.” If your aim is to improve your well being, and the well being of
    your family, then homeownership is a great way (if not the best way) to do
    it!


    I've been working as a real estate agent since 2007 (prior to that I was in
    the mortgage business) and became the broker/owner of ERA Heavener Realty in
    2011. At this point, I'm well past 400 closings in my career, and have
    personally bought/sold over 60 homes. In 2010 I was honored to have been
    nominated to the Jacksonville Business Journals 40 Under 40 crew. All of
    that to say, I've taken all of the bumps and bruises the real estate market
    has to offer, so that I can help you avoid them :)


    In addition to real estate, I love traveling with my wife to cool places,
    hanging out with our little ones (Anniston, Miles, Ava, Lily, and Leighton),
    and playing basketball (even though I have lost a step… Or, two).&nbsp;
  market: Jacksonville
  brand: Pursuit Real Estate
  brokerage:
  address: 3725 Dupont Station Ct S, Ste 1<br>Jacksonville, FL 32217
  phone: 904-405-1995
  phone_type:
  phone2:
  phone2_type:
  email: jeff@pursuitrealestate.com
  url: http://ERAHeavenerRealty.com
forms:
  sitekey: 6Lfs7jEaAAAAAOt-YLIn37b57cXONGaSNMP4RYqJ
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.findhomesjacksonville.com/cma/property-valuation/
  second_CTA_text: Home Search
  second_CTA_URL: https://www.findhomesjacksonville.com/buying
sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: What’s Your Jacksonville Home Worth?
    CTA_text: >-
      Are you thinking of selling your home or interested in learning about home
      prices in your neighborhood? We can help you.
    CTA_link_text: Free Home Value Report
    CTA_url: https://www.findhomesjacksonville.com/cma/property-valuation/
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: Looking for a Jacksonville Home?
    CTA_text2: Search the entire MLS for your Jacksonville home.
    CTA_link_text2: Search the MLS
    CTA_url2: https://www.findhomesjacksonville.com/buying
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com
socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/ERAHeavenerRealty
  linkedin_url: https://www.linkedin.com/in/jeffriber
  youtube_url: https://www.youtube.com/channel/UCdRCAdvNfzdt4fnKg2eormQ
  twitter_url:
  instagram_url: https://www.instagram.com/era.heavener/
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/jriber/
  trulia_url:
  yelp_url: https://www.yelp.com/biz/era-heavener-realty-jacksonville
  podcast_url: >-
    https://podcasts.apple.com/us/podcast/jacksonville-real-estate-podcast-with-jeff-riber/id1481267275
podcast:
  title: Jacksonville Real Estate Podcast with Jeff Riber
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the
    Jacksonville Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from ERA Real Estate - your professional
    Jacksonville Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in Jacksonville,
    home selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: Jeff Riber
images:
  client_headshot_path: /uploads/newsest-business-card-pic.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 70
  hero_text:
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#d51931'
  theme_color: '#0b3279'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
navbar_colors:
  border_bottom:
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: rgba(238, 238, 238, 0.75)
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: rgba(0, 0, 0, 0)
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: rgba(0, 0, 0, 0)
  secondary_button_text_color: '#ffffff'
