audit_header: false
title: Jacksonville Real Estate Video Blog with Jeff Riber
description: >-
  Hey, I'm Jeff. Good to meet you!


  Officially, I got my real estate license in 2007.  But the passion for real
  estate began well before that.  My Dad (and my Mom, Uncle, Granddad, Cousins,
  Sister...) was in the real estate business.  I can remember going to his
  office as a kid.  Right around the time the MLS was converting from a paper
  handbook to an online database.  And being fascinated by the idea of being
  able to see, online, listings of homes that were for sale.  I was around 11 or
  12 at the time, and can now look back to realize that was the initial spark.  


  Fast forward.  I actually began my journey as a real estate agent in 2007
  (yes, just before the "great recession") after working in the mortgage
  business for a few years. In 2011, I took on the role of broker/owner at ERA
  Heavener Realty. Then in 2023 we opened an independent brokerage, Pursuit Real
  Estate.


  Throughout my career, I have brokered over a thousand transactions and
  personally bought and sold more than 80 homes. Some years back, I was
  privileged to be nominated to the Jacksonville Business Journal's 40 Under 40
  (although 40 is clearly in the rear-view now!).


  It wasn't always easy.  I'm sure you'd say the same for accomplishments that
  have taken you years/decades?  But, thankfully, we've built a team and
  established processes capable of delivering at a high-level for the clients we
  serve.  


  Theodore Roosevelt, the 26th President, has this quote that I love: "Every
  person who invests in well-selected real estate in a growing section of a
  prosperous community adopts the surest and safest method of becoming
  independent, for real estate is the basis of wealth."  We live in a place
  (northeast Florida) and time when this still holds true!  If your goal is to
  improve your well-being and that of your family, home-ownership is undoubtedly
  the way to go.


  Beyond my professional pursuits, I love traveling alongside my wife to fun and
  exciting places (though the destinations have become less fascinating as we
  have more kids.  I.E. Disney).  Additionally, spending quality time with our
  crew, Anniston, Miles, Ava, Lily, and Leighton, keeps me on my toes. And,
  despite losing a step or two, I still love playing basketball.


  Feel free to reach out, would love to hear about what you'd like to accomplish
  in real estate!
show_custom_links: true
custom_links:
  - title: Schedule an Appointment
    url: https://calendar.app.google/7BgUMhGtpQwwpgnw9
  - title: Testimonials
    url: >-
      https://www.google.com/search?q=pursuit+real+estate+jacksonville+fl&rlz=1C1CHBF_enUS702US703&ei=7J-VZJbpCPuA0PEP5qCD-Ac&ved=0ahUKEwiWj-S7wdn_AhV7ADQIHWbQAH8Q4dUDCBA&uact=5&oq=pursuit+real+estate+jacksonville+fl&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQAzIFCCEQoAEyBQghEKsCMggIIRAWEB4QHTIICCEQFhAeEB06CAgAEIAEELADOgkIABAHEB4QsAM6CQgAEAgQHhCwAzoFCAAQgAQ6BggAEBYQHkoECEEYAVC9IliSOmDhO2gCcAB4AIABdogByA2SAQM4LjmYAQCgAQHAAQHIAQU&sclient=gws-wiz-serp
  - title: Guaranteed Offer
    url: /guaranteed-offer/
client:
  name: Jeff Riber
  title: Broker
  license_number: BK3574783
  about_markdown: >-
    Hey, I'm Jeff. Good to meet you!<br><br>Officially, I got my real estate
    license in 2007. But the passion for real estate began well before that. My
    Dad (and my Mom, Uncle, Granddad, Cousins, Sister...) was in the real estate
    business. I can remember going to his office as a kid. Right around the time
    the MLS was converting from a paper handbook to an online database. And
    being fascinated by the idea of being able to see, online, listings of homes
    that were for sale. I was around 11 or 12 at the time, and can now look back
    to realize that was the initial spark. <br><br>Fast forward. I actually
    began my journey as a real estate agent in 2007 (yes, just before the "great
    recession") after working in the mortgage business for a few years. In 2011,
    I took on the role of broker/owner at ERA Heavener Realty. Then in 2023 we
    opened an independent brokerage, Pursuit Real Estate.<br><br>Throughout my
    career, I have brokered over a thousand transactions and personally bought
    and sold more than 80 homes. Some years back, I was privileged to be
    nominated to the Jacksonville Business Journal's 40 Under 40 (although 40 is
    clearly in the rear-view now!).<br><br>It wasn't always easy. I'm sure you'd
    say the same for accomplishments that have taken you years/decades? But,
    thankfully, we've built a team and established processes capable of
    delivering at a high-level for the clients we serve. <br><br>Theodore
    Roosevelt, the 26th President, has this quote that I love: "Every person who
    invests in well-selected real estate in a growing section of a prosperous
    community adopts the surest and safest method of becoming independent, for
    real estate is the basis of wealth." We live in a place (northeast Florida)
    and time when this still holds true! If your goal is to improve your
    well-being and that of your family, home-ownership is undoubtedly the way to
    go.<br><br>Beyond my professional pursuits, I love traveling alongside my
    wife to fun and exciting places (though the destinations have become less
    fascinating as we have more kids. I.E. Disney). Additionally, spending
    quality time with our crew, Anniston, Miles, Ava, Lily, and Leighton, keeps
    me on my toes. And, despite losing a step or two, I still love playing
    basketball.<br><br>Feel free to reach out, would love to hear about what
    you'd like to accomplish in real estate!
  market: Jacksonville
  brand: Pursuit Real Estate
  brokerage:
  address: 3725 Dupont Station Ct S, Ste 1<br>Jacksonville, FL 32217
  phone: (904) 405-1995
  phone_type:
  phone2:
  phone2_type:
  email: jeff@pursuitrealestate.com
  url: https://pursuitrealestate.com
forms:
  sitekey: 6Lfs7jEaAAAAAOt-YLIn37b57cXONGaSNMP4RYqJ
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://consumer.hifello.com/p/jeffriber/664cff3ba70869002ec43b57
  second_CTA_text: Home Search
  second_CTA_URL: https://pursuitrealestate.com/properties/
sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: What’s Your Jacksonville Home Worth?
    CTA_text: >-
      Are you thinking of selling your home or interested in learning about home
      prices in your neighborhood? We can help you.
    CTA_link_text: Free Home Value Report
    CTA_url: https://consumer.hifello.com/p/jeffriber/664cff3ba70869002ec43b57
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: Looking for a Jacksonville Home?
    CTA_text2: Search the entire MLS for your Jacksonville home.
    CTA_link_text2: Search the MLS
    CTA_url2: https://pursuitrealestate.com/properties/
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com
socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/PursuitRealEstateJax/
  linkedin_url: https://www.linkedin.com/in/jeffriber
  youtube_url: https://www.youtube.com/@pursuitrealestate
  twitter_url:
  instagram_url: https://www.instagram.com/pursuitrealestatejax/
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/jriber/
  trulia_url:
  yelp_url: https://www.yelp.com/biz/era-heavener-realty-jacksonville
  podcast_url: >-
    https://podcasts.apple.com/us/podcast/jacksonville-real-estate-podcast-with-jeff-riber/id1481267275
podcast:
  title: Jacksonville Real Estate Podcast with Jeff Riber
  categories:
    - Education
  image: /uploads/jeff-riber-podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the
    Jacksonville Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from Pursuit Real Estate - your
    professional Jacksonville Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in Jacksonville,
    home selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: Jeff Riber
images:
  client_headshot_path: /uploads/newsest-business-card-pic.jpg
  hero_logo_path: /uploads/pursuit-real-estate-logo-horizontal-v1.png
  logo_width_number: 30
  hero_text:
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#0a369d'
  theme_color: '#0a369d'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
navbar_colors:
  border_bottom:
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: rgba(238, 238, 238, 0.75)
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: rgba(0, 0, 0, 0)
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: rgba(0, 0, 0, 0)
  secondary_button_text_color: '#ffffff'
